language: go

go:
  - 1.7
  - tip

before_install:
  - wget 'https://releases.hashicorp.com/consul/0.7.1/consul_0.7.1_linux_amd64.zip'
  - unzip consul_0.7.1_linux_amd64.zip
  - ./consul --version
  - wget 'https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip'
  - unzip gnatsd-v0.9.4-linux-amd64.zip
  - ./gnatsd -v

install: go get -t ./...

script:
  - ./consul agent -dev &
  - ./gnatsd -D &
  - sleep 1
  - go test -v ./...
