language: go

go:
  - 1.7
  - tip

before_install:
  - wget 'https://releases.hashicorp.com/consul/0.7.1/consul_0.7.1_linux_amd64.zip'
  - unzip consul_0.7.1_linux_amd64.zip
  - ./consul --version

install: go get -t ./...

script:
  - ./consul agent -dev &
  - sleep 1
  - go test -v ./...
