
dist: trusty

language: go

go:
  - 1.8
  - 1.9
  - tip

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:8500:8500 -p 127.0.0.1:8600:8600 consul:latest
  - docker run -d -p 127.0.0.1:4222:4222 nats:latest

install: go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - go test -v ./...
